image: docker:20.10.16
stages:
  - lint
  - test

precommit:
  stage: lint
  image: python:3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install poetry
    - poetry install pre-commit
  script:
    - pre-commit run --all-files

pytest:
  stage: test
  only:
    - merge_requests
    - main
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker compose up --build
  script:
    - docker compose run --rm fastapi-live-chat mypy .
    - docker compose -f test.yml run django-market-power-test pytest -n auto --create-db
    - docker compose -f test.yml down
    - docker image rm postgres_market_power_test

