image: docker:20.10.16
stages:
  - lint
  - test

precommit:
  stage: lint
  only:
    - merge_requests
    - main
  image: python:3.12
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install poetry
    - poetry install --no-root --only=dev
    - pip install pre-commit
  script:
    - pre-commit run --all-files

pytest:
  stage: test
  only:
    - merge_requests
    - main
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker compose -f docker-compose.test.yml build
    - docker compose -f docker-compose.test.yml up -d
  script:
    - docker compose -f docker-compose.test.yml run fastapi-live-chat-test pytest
  after_script:
    - docker compose -f docker-compose.test.yml down --remove-orphans
