networks:
  live_chat_network:
    driver: bridge

volumes:
  postgres-local-data:
  redis-local-data:
  minio_local_data:

services:
  fastapi-live-chat-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:
      live_chat_fastapi_local
    restart: always
    ports:
      - "8000:8000"
    command: python live_chat
    env_file:
      - .envs/.local/.env
    depends_on:
      postgres-live-chat-local:
        condition: service_healthy
      redis-live-chat-local:
        condition: service_healthy
      minio-live-chat-local:
        condition: service_healthy
    networks:
      - live_chat_network

  vue-live-chat-local:
    build:
      context: ./frontend
    container_name: vue_live_chat_local
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - fastapi-live-chat-local
    networks:
      - live_chat_network

  postgres-live-chat-local:
    image: postgres:16.3-bullseye
    container_name: postgres_live_chat_local
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.env
    restart: always
    healthcheck:
      test: pg_isready -U postgres-live-chat -d postgres_live_chat_local
      interval: 2s
      timeout: 3s
      retries: 40
    networks:
      - live_chat_network

  migrator-live-chat-local:
    build:
      context: .
    container_name: migrator_live_chat_local
    env_file:
      - .envs/.local/.env
    restart: "no"
    command: alembic upgrade head
    depends_on:
      postgres-live-chat-local:
        condition: service_healthy
    networks:
      - live_chat_network

  redis-live-chat-local:
    image: bitnami/redis:6.2.5
    restart: always
    env_file:
      - .envs/.local/.env
    volumes:
      - redis-local-data:/var/lib/postgresql/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50
    networks:
      - live_chat_network

  minio-live-chat-local:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
    container_name: minio_live_chat_local
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: mc ready local
      interval: 10s
      timeout: 20s
      retries: 3
    volumes:
      - minio_local_data:/data
    env_file:
      - .envs/.local/.env
    command: server --console-address ":9001" /data
    networks:
      - live_chat_network
