"""add original_message_id field

Revision ID: 97b1e7bdc4ee
Revises: fe6833b58a20
Create Date: 2024-12-03 15:39:53.795812

"""

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97b1e7bdc4ee"
down_revision = "fe6833b58a20"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deleted_message",
        sa.Column(
            "original_message_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deleted_message", "original_message_id")
    # ### end Alembic commands ###
