"""add last_message_content field

Revision ID: 7726106a8626
Revises: c5ff002c10ed
Create Date: 2024-12-16 09:49:52.162658

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7726106a8626"
down_revision = "c5ff002c10ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat", sa.Column("last_message_content", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "last_message_content")
    # ### end Alembic commands ###
