"""rename last_login to last_online

Revision ID: f746ec6f3d48
Revises: 0c4adf5ddab8
Create Date: 2024-12-19 09:40:47.549929

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f746ec6f3d48"
down_revision = "0c4adf5ddab8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("last_online", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("user", "last_login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "last_login",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "last_online")
    # ### end Alembic commands ###
