"""create chat_participant model

Revision ID: dde630e0f286
Revises: 05152456aa1c
Create Date: 2024-11-12 10:53:30.474243

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dde630e0f286"
down_revision = "05152456aa1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_participant",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_participant")
    # ### end Alembic commands ###
