"""add reply to message

Revision ID: 1a1e95303233
Revises: 3694587be8c0
Create Date: 2025-01-24 17:23:42.822547

"""

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a1e95303233"
down_revision = "3694587be8c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deleted_message",
        sa.Column(
            "parent_message_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "deleted_message", "message", ["parent_message_id"], ["id"]
    )
    op.add_column(
        "draft_message",
        sa.Column(
            "parent_message_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        None, "draft_message", "message", ["parent_message_id"], ["id"]
    )
    op.add_column(
        "message",
        sa.Column(
            "parent_message_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(None, "message", "message", ["parent_message_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_column("message", "parent_message_id")
    op.drop_constraint(None, "draft_message", type_="foreignkey")
    op.drop_column("draft_message", "parent_message_id")
    op.drop_constraint(None, "deleted_message", type_="foreignkey")
    op.drop_column("deleted_message", "parent_message_id")
    # ### end Alembic commands ###
