"""Add tasks

Revision ID: f4c8a8f6b590
Revises: db0a6bd98f4a
Create Date: 2025-02-07 11:48:55.424224

"""

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "f4c8a8f6b590"
down_revision = "1a1e95303233"
branch_labels = None
depends_on = None


def upgrade() -> None:
    enum_type = ENUM("SUMMARIZATION", name="tasktype", create_type=False)
    enum_type.create(op.get_bind(), checkfirst=True)
    enum_status = ENUM(
        "IN_PROGRESS", "SUCCESS", "ERROR", name="taskstatus", create_type=False
    )
    enum_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("type", enum_type, nullable=False),
        sa.Column("status", enum_status, nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "chat_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    # ### end Alembic commands ###
