"""add ban user

Revision ID: 360491ed5559
Revises: bcdcde196734
Create Date: 2025-01-09 11:01:10.735567

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "360491ed5559"
down_revision = "bcdcde196734"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_banned", sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET is_banned = FALSE')
    op.alter_column("user", "is_banned", nullable=False)
    op.add_column(
        "user", sa.Column("ban_reason", sa.String(length=1048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "ban_reason")
    op.drop_column("user", "is_banned")
    # ### end Alembic commands ###
