"""add forward messages

Revision ID: e69e39c81804
Revises: 1a1e95303233
Create Date: 2025-02-04 11:57:55.334044

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69e39c81804'
down_revision = '1a1e95303233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('forwarded_message_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'message', 'message', ['forwarded_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'forwarded_message_id')
    # ### end Alembic commands ###
